version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: poetry config settings.virtualenvs.in-project true
      - run:
          command: |
            poetry run make install
      - run:
          command: |
            poetry run make tests
      - run:
          command: |
            poetry run make lint

workflows:
  version: 2
  main:
    jobs:
      - test
